In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.1'

In [4]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [5]:
type(array1)

numpy.ndarray

In [8]:
array2=np.array([
                  [1,2],
                  [3,4]
])
array2

array([[1, 2],
       [3, 4]])

In [10]:
array2d=np.array([
                  [1,2,3.3],
                  [4,5,6.6]    
])
array2d


array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [14]:
arrex=np.array([
                [
                 [1,2],
                 [3,4]
               ],
               [
                   [5,6],
                   [7,8]
               ]
])
arrex

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
array3=np.array([
                [
                   [1,2,3],
                   [4,5,6],
                   [7,8,9]
                ],
                  [
                      [10,11,12],
                      [13,14,15],
                      [16,17,18]
                  ]
])
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
array4=np.array((12,13,14))
array4

array([12, 13, 14])

In [17]:
print(array1.ndim)

1


In [18]:
print(array2.ndim)

2


In [19]:
print(array4.ndim)

1


In [20]:
print(array3.ndim)

3


In [21]:
array5=np.array([1,2,3,4],ndmin=4)
array5

array([[[[1, 2, 3, 4]]]])

In [22]:
array5.shape

(1, 1, 1, 4)

In [23]:
array1.shape

(3,)

In [24]:
array2.shape

(2, 2)

In [25]:
array3.shape

(2, 3, 3)

In [26]:
array4.shape

(3,)

In [27]:
array2

array([[1, 2],
       [3, 4]])

In [29]:
array2d[0][1]

2.0

In [30]:
array2d[1][0]

4.0

In [32]:
array2d[0][2]

3.3

In [33]:
for x in range(0,2):
    for y in range(0,3):
        print(array2d[x][y])

1.0
2.0
3.3
4.0
5.0
6.6


In [34]:
array1.dtype

dtype('int32')

In [35]:
array2d.dtype

dtype('float64')

In [37]:
array5=np.array([1,2,3,4,5],dtype='S')

In [38]:
array5

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [40]:
array2dconv=array2d.astype('i')
array2dconv

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [41]:
array2dconv=array2d.astype('f')
array2dconv

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]], dtype=float32)

In [42]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [43]:
num=np.ones(3)
num

array([1., 1., 1.])

In [44]:
num3d=np.ones((2,3,3))
num3d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
numszero=np.zeros((3,2),dtype=int)
numszero

array([[0, 0],
       [0, 0],
       [0, 0]])

In [47]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [50]:
a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [51]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[5, 4, 2],
       [2, 5, 3]])

In [52]:
np.concatenate([array1,array4])

array([ 1,  2,  3, 12, 13, 14])

In [53]:
flatarr=array3.flatten()
flatarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [54]:
np.reshape(flatarr[:4],(2,2))

array([[1, 2],
       [3, 4]])

In [55]:
flatarr[:4]

array([1, 2, 3, 4])

In [56]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [60]:
import pandas as pd
df=pd.DataFrame(array2d)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6